### ISSUE TITLE
BUG: pyflakes errors

### ISSUE THREAD

**Issue by dengemann** [pik-copan/pycopanbehave#15]
Fixes and cleanup in 1a573e8ae42337158c0053492ba01cff9da99dd4 revealed two errors.

cf https://www.dropbox.com/s/ut1okradf5ptfe7/Screenshot%202016-06-28%2015.48.05.png?dl=0
red tags.

cc @jdonges @carlschleussner

**Comment by jdonges** [comment]
Solved with commits 0a6050aa6a7f971520143301a879c3c78281316a and 52db3cb37a043447b667a32901149a3793446ab7
